import { LANGUAGE } from "../../utils/constants"

export default {
    [LANGUAGE.EN]: {
        Yes: 'Yes',
        No: 'No',
        AttendQ: 'Will you be able to attend our event?',
        Menu: 'What type of menu do you prefer?',
        Plus1: 'Do you have a plus 1?',
        Tel: 'Do you wish to provide a phone number?',
        Submit: 'Press here to let us know!',
        ChangeInfo: 'Press here to resubmit the form',
        Attending: 'Attending',
        Meal: 'Meal',
        Name: 'Name',
        false: 'No',
        true: 'Yes',
        Mentions: 'Mentions',
        MentionsQ: 'Do you have any mentions?',
        MentionsPlaceholder: 'Alergens...',
        standard: 'Standard',
        vegetarian: 'Vegetarian',
        'lacto-vegetarian': 'Lacto Vegetarian'
    },
    [LANGUAGE.RO]: {
        Yes: 'Da',
        No: 'Nu',
        AttendQ: 'Confirmați prezența la eveniment?',
        Menu: 'Ce tip de meniu preferați?',
        Plus1: 'Veniți însoțit de încă o persoană?',
        Tel: 'Doriți să ne lăsați un nr. de telefon?',
        Submit: 'Apăsați aici pentru a ne anunța!',
        ChangeInfo: 'Apăsați aici pentru a schimba detaliile',
        Attending: 'Participați',
        Meal: 'Meniu',
        Name: 'Nume',
        false: 'Nu',
        true: 'Da',
        Mentions: 'Mențiuni',
        MentionsQ: 'Doriți să agăugați mențiuni?',
        MentionsPlaceholder: 'Alergeni...',
        standard: 'Standard',
        vegetarian: 'Vegetarian',
        'lacto-vegetarian': 'Lacto Vegetarian'
    },
}
